const ScheduleItem = [
  {
    id: 1,
    title: "피그마 완성하기",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 2,
    title: "저녁 먹기",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 3,
    title: "Choose New Page",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 4,
    title: "피그마 완성하기",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 5,
    title: "저녁 먹기",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 6,
    title: "Choose New Page",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 7,
    title: "피그마 완성하기",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 8,
    title: "저녁 먹기",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 9,
    title: "Choose New Page",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 10,
    title: "피그마 완성하기",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 11,
    title: "저녁 먹기",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 12,
    title: "Choose New Page",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 13,
    title: "피그마 완성하기",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 14,
    title: "저녁 먹기",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 15,
    title: "Choose New Page",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 16,
    title: "피그마 완성하기",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 17,
    title: "저녁 먹기",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 18,
    title: "Choose New Page",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 19,
    title: "피그마 완성하기",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 20,
    title: "저녁 먹기",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
  {
    id: 21,
    title: "Choose New Page",
    description: "Mobile UI Kit",
    startTime: "11:30",
    endTime: "14:30",
  },
];

export default ScheduleItem;